// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/stockItems.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace SharedData.proto {
  public static partial class StockItems
  {
    static readonly string __ServiceName = "stockItems.StockItems";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SharedData.proto.AllStockItemRequest> __Marshaller_stockItems_AllStockItemRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SharedData.proto.AllStockItemRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SharedData.proto.AllStockItemReply> __Marshaller_stockItems_AllStockItemReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SharedData.proto.AllStockItemReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SharedData.proto.StockItemsCurrentPriceRequest> __Marshaller_stockItems_StockItemsCurrentPriceRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SharedData.proto.StockItemsCurrentPriceRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SharedData.proto.StockItemsCurrentPriceReply> __Marshaller_stockItems_StockItemsCurrentPriceReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SharedData.proto.StockItemsCurrentPriceReply.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::SharedData.proto.AllStockItemRequest, global::SharedData.proto.AllStockItemReply> __Method_GetAllStockItem = new grpc::Method<global::SharedData.proto.AllStockItemRequest, global::SharedData.proto.AllStockItemReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAllStockItem",
        __Marshaller_stockItems_AllStockItemRequest,
        __Marshaller_stockItems_AllStockItemReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::SharedData.proto.StockItemsCurrentPriceRequest, global::SharedData.proto.StockItemsCurrentPriceReply> __Method_GetStockItemsCurrentPrice = new grpc::Method<global::SharedData.proto.StockItemsCurrentPriceRequest, global::SharedData.proto.StockItemsCurrentPriceReply>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetStockItemsCurrentPrice",
        __Marshaller_stockItems_StockItemsCurrentPriceRequest,
        __Marshaller_stockItems_StockItemsCurrentPriceReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::SharedData.proto.StockItemsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of StockItems</summary>
    [grpc::BindServiceMethod(typeof(StockItems), "BindService")]
    public abstract partial class StockItemsBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::SharedData.proto.AllStockItemReply> GetAllStockItem(global::SharedData.proto.AllStockItemRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task GetStockItemsCurrentPrice(global::SharedData.proto.StockItemsCurrentPriceRequest request, grpc::IServerStreamWriter<global::SharedData.proto.StockItemsCurrentPriceReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for StockItems</summary>
    public partial class StockItemsClient : grpc::ClientBase<StockItemsClient>
    {
      /// <summary>Creates a new client for StockItems</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public StockItemsClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for StockItems that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public StockItemsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected StockItemsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected StockItemsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::SharedData.proto.AllStockItemReply GetAllStockItem(global::SharedData.proto.AllStockItemRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllStockItem(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::SharedData.proto.AllStockItemReply GetAllStockItem(global::SharedData.proto.AllStockItemRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAllStockItem, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::SharedData.proto.AllStockItemReply> GetAllStockItemAsync(global::SharedData.proto.AllStockItemRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllStockItemAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::SharedData.proto.AllStockItemReply> GetAllStockItemAsync(global::SharedData.proto.AllStockItemRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAllStockItem, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::SharedData.proto.StockItemsCurrentPriceReply> GetStockItemsCurrentPrice(global::SharedData.proto.StockItemsCurrentPriceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStockItemsCurrentPrice(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::SharedData.proto.StockItemsCurrentPriceReply> GetStockItemsCurrentPrice(global::SharedData.proto.StockItemsCurrentPriceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetStockItemsCurrentPrice, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override StockItemsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new StockItemsClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(StockItemsBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAllStockItem, serviceImpl.GetAllStockItem)
          .AddMethod(__Method_GetStockItemsCurrentPrice, serviceImpl.GetStockItemsCurrentPrice).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, StockItemsBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetAllStockItem, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SharedData.proto.AllStockItemRequest, global::SharedData.proto.AllStockItemReply>(serviceImpl.GetAllStockItem));
      serviceBinder.AddMethod(__Method_GetStockItemsCurrentPrice, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::SharedData.proto.StockItemsCurrentPriceRequest, global::SharedData.proto.StockItemsCurrentPriceReply>(serviceImpl.GetStockItemsCurrentPrice));
    }

  }
}
#endregion
