FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copy everything
COPY . ./
# Restore as distinct layers

RUN dotnet restore "SharedData/SharedData.csproj"
RUN dotnet restore "test1/test1Console.csproj"

# Build and publish a release
WORKDIR "/app/test1"
RUN dotnet publish "test1Console.csproj" -c Release -o /app/out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "test1Console.dll"]